<a href="https://colab.research.google.com/github/ukhyun-lee/stock_market_analysis/blob/main/%EC%A4%91%EA%B8%89/10%EC%9D%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B51.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
data = load_iris(as_frame=True)

In [ ]:
iris = data.frame

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(iris.iloc[:,:-1], iris.target, stratify=iris.target)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
grid_knn = GridSearchCV(KNeighborsClassifier(), {'n_neighbors' : range(3,21,2)})

In [ ]:
grid_lr = GridSearchCV(LogisticRegression(), {'C':[1,10,100,1000]})

In [ ]:
grid_dt = GridSearchCV(DecisionTreeClassifier(), {'splitter' : ["best", "random"]} )

In [ ]:
grid_knn.fit(X_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(3, 21, 2)})

In [ ]:
grid_knn.best_params_

{'n_neighbors': 5}

In [ ]:
grid_knn.best_score_

0.9648221343873518

In [ ]:
grid_lr.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 100, 1000]})

In [ ]:
knn = KNeighborsClassifier(**grid_knn.best_params_)

In [ ]:
grid_lr.best_params_

{'C': 1}

In [ ]:
lr = LogisticRegression(**grid_lr.best_params_)

In [ ]:
grid_dt.fit(X_train,y_train)

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'splitter': ['best', 'random']})

In [ ]:
grid_dt.best_params_

{'splitter': 'best'}

In [ ]:
dt = DecisionTreeClassifier(**grid_dt.best_params_)

# ensemble

## voting

In [ ]:
1. knn
2. lr
3. dt

SyntaxError: ignored

In [ ]:
iris

In [ ]:
predict => 3,3,3,3

In [ ]:
1. knn > setosa
2. lr > virginica
3. dt > virginica

In [ ]:
knn : 3
lr : 2
dt : 1

In [ ]:
knn (k=5)
knn (k=7)

In [ ]:
from sklearn.model_selection import cross_val_predict, cross_val_score, cross_validate

In [ ]:
cross_validate(KNeighborsClassifier(), X_train,y_train, cv=10)

{'fit_time': array([0.0052433 , 0.00568151, 0.00500846, 0.00428486, 0.00312281,
        0.00202203, 0.00194883, 0.00193501, 0.00297451, 0.00211215]),
 'score_time': array([0.00468612, 0.00908899, 0.00425744, 0.00749493, 0.00273013,
        0.00264049, 0.0025847 , 0.00252271, 0.00334334, 0.0026927 ]),
 'test_score': array([1.        , 0.91666667, 0.81818182, 0.90909091, 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ])}

In [ ]:
result = cross_validate(KNeighborsClassifier(), X_train,y_train, cv=10)

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(result)

fit_time  score_time  test_score
0  0.003346    0.003725    1.000000
1  0.003964    0.003728    0.916667
2  0.002074    0.002589    0.818182
3  0.001997    0.002617    0.909091
4  0.002511    0.004744    1.000000
5  0.003012    0.008255    1.000000
6  0.002605    0.004314    1.000000
7  0.003072    0.003360    1.000000
8  0.002168    0.002718    1.000000
9  0.001946    0.003220    1.000000

In [ ]:
cross_val_score(KNeighborsClassifier(), X_train,y_train, cv=10)

array([1.        , 0.91666667, 0.81818182, 0.90909091, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [ ]:
cross_val_predict(KNeighborsClassifier(), X_train, y_train, cv=10)

array([0, 2, 2, 2, 0, 2, 0, 0, 2, 1, 0, 1, 2, 1, 2, 0, 2, 1, 2, 1, 2, 2,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 2, 1, 0, 0, 2, 1, 0, 2, 1, 2, 2, 1, 1,
       1, 0, 0, 2, 1, 0, 0, 1, 0, 1, 2, 1, 2, 0, 1, 1, 0, 0, 2, 2, 1, 0,
       0, 1, 1, 2, 2, 0, 1, 1, 2, 0, 1, 2, 1, 0, 0, 0, 2, 0, 2, 1, 1, 0,
       1, 2, 2, 2, 0, 1, 1, 1, 1, 1, 0, 0, 2, 2, 1, 1, 1, 0, 2, 0, 2, 0,
       2, 1])

In [ ]:
X_train,X_test,y_train,y_test = \
train_test_split(iris.iloc[:,:-1], iris.target, stratify=iris.target, random_state=3)

In [ ]:
import numpy as np

In [ ]:
from sklearn.utils import resample

In [ ]:
resample(np.array([1,2,3,4,5,6]), n_samples=3)

array([5, 6, 2])

In [ ]:
from sklearn.ensemble import BaggingClassifier

In [ ]:
bc = BaggingClassifier()

In [ ]:
bc.fit(X_train,y_train)

BaggingClassifier()

In [ ]:
bc.predict([[3,3,3,3]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but BaggingClassifier was fitted with feature names
  warnings.warn(


array([2])

In [ ]:
vars(bc)

{'estimator': None,
 'n_estimators': 10,
 'estimator_params': (),
 'base_estimator': 'deprecated',
 'max_samples': 1.0,
 'max_features': 1.0,
 'bootstrap': True,
 'bootstrap_features': False,
 'oob_score': False,
 'warm_start': False,
 'n_jobs': None,
 'random_state': None,
 'verbose': 0,
 'feature_names_in_': array(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
        'petal width (cm)'], dtype=object),
 'n_features_in_': 4,
 '_n_samples': 112,
 'classes_': array([0, 1, 2]),
 'n_classes_': 3,
 'estimator_': DecisionTreeClassifier(),
 '_max_samples': 112,
 '_max_features': 4,
 'estimators_': [DecisionTreeClassifier(random_state=1210977655),
  DecisionTreeClassifier(random_state=1082590361),
  DecisionTreeClassifier(random_state=2047253042),
  DecisionTreeClassifier(random_state=1925212487),
  DecisionTreeClassifier(random_state=1862801593),
  DecisionTreeClassifier(random_state=1947482177),
  DecisionTreeClassifier(random_state=1787997610),
  DecisionTreeClassifier(ran

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc = RandomForestClassifier()

In [ ]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
rfc.feature_importances_

array([0.09011997, 0.02547063, 0.40373593, 0.48067348])

In [ ]:
from sklearn.ensemble import VotingClassifier

In [ ]:
vc = VotingClassifier([('knn', KNeighborsClassifier()),
                       ('dt', DecisionTreeClassifier()),
                       ('lr', LogisticRegression())], voting='hard', weights=[2,1,3], verbose=True)

In [ ]:
vc

VotingClassifier(estimators=[('knn', KNeighborsClassifier()),
                             ('dt', DecisionTreeClassifier()),
                             ('lr', LogisticRegression())],
                 verbose=True, weights=[2, 1, 3])

In [ ]:
vc.fit(X_train,y_train)

[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Voting] ....................... (2 of 3) Processing dt, total=   0.0s
[Voting] ....................... (3 of 3) Processing lr, total=   0.0s


VotingClassifier(estimators=[('knn', KNeighborsClassifier()),
                             ('dt', DecisionTreeClassifier()),
                             ('lr', LogisticRegression())],
                 verbose=True, weights=[2, 1, 3])

In [ ]:
vc.transform([[3,3,3,3]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[1, 2, 0]])

In [ ]:
vc.predict([[3,3,3,3]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [ ]:
vars(vc)

{'estimators': [('knn', KNeighborsClassifier()),
  ('dt', DecisionTreeClassifier()),
  ('lr', LogisticRegression())],
 'voting': 'hard',
 'weights': [2, 1, 3],
 'n_jobs': None,
 'flatten_transform': True,
 'verbose': True,
 'le_': LabelEncoder(),
 'classes_': array([0, 1, 2]),
 'estimators_': [KNeighborsClassifier(),
  DecisionTreeClassifier(),
  LogisticRegression()],
 'named_estimators_': {'knn': KNeighborsClassifier(),
  'dt': DecisionTreeClassifier(),
  'lr': LogisticRegression()},
 'feature_names_in_': array(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
        'petal width (cm)'], dtype=object)}

In [ ]:
knn

KNeighborsClassifier()

In [ ]:
knn = KNeighborsClassifier()

In [ ]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
knn.predict_proba([[3,3,3,3]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([[0. , 0.8, 0.2]])

In [ ]:
knn.predict([[3,3,3,3]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([1])

In [ ]:
lr.predict_proba

<bound method LogisticRegression.predict_proba of LogisticRegression(C=1)>

In [ ]:
lr.decision_function

<bound method LinearClassifierMixin.decision_function of LogisticRegression(C=1)>

In [ ]:
lr.predict_log_proba

<bound method LogisticRegression.predict_log_proba of LogisticRegression(C=1)>

In [ ]:
dt.predict_proba

<bound method DecisionTreeClassifier.predict_proba of DecisionTreeClassifier()>

In [ ]:
dt.decision_path

<bound method BaseDecisionTree.decision_path of DecisionTreeClassifier()>

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
grid = GridSearchCV(vc, {'weights':[[1,1,1],[1,2,3],[1,3,1]]})

In [ ]:
grid.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Voting] ....................... (2 of 3) Processing dt, total=   0.0s
[Voting] ....................... (3 of 3) Processing lr, total=   0.0s
[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Voting] ....................... (2 of 3) Processing dt, total=   0.0s
[Voting] ....................... (3 of 3) Processing lr, total=   0.0s
[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Voting] ....................... (2 of 3) Processing dt, total=   0.0s
[Voting] ....................... (3 of 3) Processing lr, total=   0.0s
[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Voting] ....................... (2 of 3) Processing dt, total=   0.0s
[Voting] ....................... (3 of 3) Processing lr, total=   0.0s
[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Voting] ....................... (2 of 3) Processing dt, total=   0.0s
[Votin

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

[Voting] ....................... (3 of 3) Processing lr, total=   0.0s
[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Voting] ....................... (2 of 3) Processing dt, total=   0.0s
[Voting] ....................... (3 of 3) Processing lr, total=   0.0s
[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Voting] ....................... (2 of 3) Processing dt, total=   0.0s
[Voting] ....................... (3 of 3) Processing lr, total=   0.0s
[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Voting] ....................... (2 of 3) Processing dt, total=   0.0s
[Voting] ....................... (3 of 3) Processing lr, total=   0.0s
[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Voting] ....................... (2 of 3) Processing dt, total=   0.0s
[Voting] ....................... (3 of 3) Processing lr, total=   0.0s
[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Votin

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Voting] ....................... (2 of 3) Processing dt, total=   0.0s
[Voting] ....................... (3 of 3) Processing lr, total=   0.0s
[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Voting] ....................... (2 of 3) Processing dt, total=   0.0s
[Voting] ....................... (3 of 3) Processing lr, total=   0.0s
[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Voting] ....................... (2 of 3) Processing dt, total=   0.0s
[Voting] ....................... (3 of 3) Processing lr, total=   0.0s
[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Voting] ....................... (2 of 3) Processing dt, total=   0.0s
[Voting] ....................... (3 of 3) Processing lr, total=   0.0s
[Voting] ...................... (1 of 3) Processing knn, total=   0.0s
[Voting] ....................... (2 of 3) Processing dt, total=   0.0s
[Votin

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(estimator=VotingClassifier(estimators=[('knn',
                                                     KNeighborsClassifier()),
                                                    ('dt',
                                                     DecisionTreeClassifier()),
                                                    ('lr',
                                                     LogisticRegression())],
                                        verbose=True, weights=[2, 1, 3]),
             param_grid={'weights': [[1, 1, 1], [1, 2, 3], [1, 3, 1]]})

In [ ]:
grid.best_params_

{'weights': [1, 1, 1]}

In [ ]:
k=5,7,9,3,11

In [ ]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

In [ ]:
ada = AdaBoostClassifier()

In [ ]:
ada.fit(X_train,y_train)

AdaBoostClassifier()

In [ ]:
ada.

SyntaxError: ignored

In [ ]:
import xgboost

In [ ]:
import lightgbm

In [ ]:
!pip install catboost

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.6/98.6 MB 8.7 MB/s eta 0:00:00


In [ ]:
import catboost

In [ ]:
from sklearn.ensemble import StackingClassifier

In [ ]:
sc = StackingClassifier([('knn', KNeighborsClassifier()),
                         ('dt', DecisionTreeClassifier())])

In [ ]:
sc.fit(X_train,y_train)

StackingClassifier(estimators=[('knn', KNeighborsClassifier()),
                               ('dt', DecisionTreeClassifier())])