<a href="https://colab.research.google.com/github/ukhyun-lee/stock_market_analysis/blob/main/%EC%A4%91%EA%B8%89/12%EC%9D%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B55.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
pd.to_datetime
pd.to_timedelta

<function pandas.core.tools.timedeltas.to_timedelta(arg: 'str | int | float | timedelta | list | tuple | range | ArrayLike | Index | Series', unit: 'UnitChoices | None' = None, errors: 'DateTimeErrorChoices' = 'raise') -> 'Timedelta | TimedeltaIndex | Series'>

##  frequent 여부 확인 주의!

In [45]:
index = pd.DatetimeIndex(['2023-07-11','2023-07-10','2023-07-11'])

In [46]:
index

DatetimeIndex(['2023-07-11', '2023-07-10', '2023-07-11'], dtype='datetime64[ns]', freq=None)

##

In [ ]:
index.freq = 'D'   #  error 경우에 따라서 변경 가능 여부

In [48]:
index

DatetimeIndex(['2023-07-11', '2023-07-10', '2023-07-11'], dtype='datetime64[ns]', freq=None)

In [49]:
index.to_period('D')    # datetimeindex에서 periodindex로 바뀜

PeriodIndex(['2023-07-11', '2023-07-10', '2023-07-11'], dtype='period[D]')

In [50]:
pi = index.to_period('D')

In [51]:
pi

PeriodIndex(['2023-07-11', '2023-07-10', '2023-07-11'], dtype='period[D]')

In [52]:
pi.min()

Period('2023-07-10', 'D')

In [53]:
pi.max()

Period('2023-07-11', 'D')

In [54]:
index

DatetimeIndex(['2023-07-11', '2023-07-10', '2023-07-11'], dtype='datetime64[ns]', freq=None)

In [60]:
td = index - index[0]

In [61]:
td

TimedeltaIndex(['0 days', '-1 days', '0 days'], dtype='timedelta64[ns]', freq=None)

In [62]:
data = pd.Series([1,2,3], index=td)

In [63]:
data

0 days     1
-1 days    2
0 days     3
dtype: int64

In [64]:
data[-1]

3

In [65]:
data['0']

0 days    1
0 days    3
dtype: int64

In [ ]:
data['-1']   ##  error 마이너스 값 안됨, 후는 되지만

In [67]:
data[1:-1]   ## 꼼수

-1 days    2
dtype: int64

In [55]:
data = pd.Series([1,2,3], index=pi)

In [56]:
data

2023-07-11    1
2023-07-10    2
2023-07-11    3
Freq: D, dtype: int64

In [57]:
data = pd.Series([1,2,3], index=index)

In [58]:
data

2023-07-11    1
2023-07-10    2
2023-07-11    3
dtype: int64

In [59]:
data.sort_index()

2023-07-10    2
2023-07-11    1
2023-07-11    3
dtype: int64

In [9]:
data.info()

<class 'pandas.core.series.Series'>
DatetimeIndex: 3 entries, 2023-07-09 to 2023-07-10
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 48.0 bytes


In [13]:
data['2023-07-10']

2023-07-10    2
2023-07-10    3
dtype: int64

#datetime 인덱스 또는 timedelta 인덱스 일 때
->시간에따라 내가 원하는 것 뽑을 수 있음
# index 같아도됨 (??)

In [21]:
index = pd.date_range('2023-01','2025-12', freq='M')

In [22]:
index

DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31',
               '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31',
               '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31',
               '2025-09-30', '2025-10-31', '2025-11-30'],
              dtype='datetime64[ns]', freq='M')

In [23]:
import numpy as np

In [24]:
data = np.random.randn(35)

In [25]:
d = pd.Series(data, index=index)

In [27]:
d['2023-01':'2023-05']

2023-01-31   -0.305731
2023-02-28   -1.141798
2023-03-31    0.209230
2023-04-30   -1.701960
2023-05-31    0.835484
Freq: M, dtype: float64

## index
- datetimeindex => 가장 큰범위 =>  유연, 규칙 (freq없이)   / date_range
- periodindex  => 기간 명시                               / period_range
------------------------------------------ 시계열
- timedeltaindex =>  시간의 차                            / timedelta_range

In [68]:
pd.date_range

<function pandas.core.indexes.datetimes.date_range(start=None, end=None, periods=None, freq=None, tz=None, normalize: 'bool' = False, name: 'Hashable' = None, closed: "Literal['left', 'right'] | None | lib.NoDefault" = <no_default>, inclusive: 'IntervalClosedType | None' = None, **kwargs) -> 'DatetimeIndex'>

In [70]:
pd.period_range('2023-06', '2023-07')

PeriodIndex(['2023-06-01', '2023-06-02', '2023-06-03', '2023-06-04',
             '2023-06-05', '2023-06-06', '2023-06-07', '2023-06-08',
             '2023-06-09', '2023-06-10', '2023-06-11', '2023-06-12',
             '2023-06-13', '2023-06-14', '2023-06-15', '2023-06-16',
             '2023-06-17', '2023-06-18', '2023-06-19', '2023-06-20',
             '2023-06-21', '2023-06-22', '2023-06-23', '2023-06-24',
             '2023-06-25', '2023-06-26', '2023-06-27', '2023-06-28',
             '2023-06-29', '2023-06-30', '2023-07-01'],
            dtype='period[D]')

In [72]:
pd.period_range('2023-06-01', periods=10)

PeriodIndex(['2023-06-01', '2023-06-02', '2023-06-03', '2023-06-04',
             '2023-06-05', '2023-06-06', '2023-06-07', '2023-06-08',
             '2023-06-09', '2023-06-10'],
            dtype='period[D]')

In [73]:
pd.timedelta_range('0', periods=10)

TimedeltaIndex(['0 days', '1 days', '2 days', '3 days', '4 days', '5 days',
                '6 days', '7 days', '8 days', '9 days'],
               dtype='timedelta64[ns]', freq='D')

#  to_

In [74]:
import numpy as np

In [75]:
np.add  #=> ufunction(universial function)과 비슷

<ufunc 'add'>

In [76]:
np.add(1,2)

3

In [77]:
np.add([1,2,3],[4,3,4])

array([5, 5, 7])

# fancy indexing (numpy advanced indexing)

In [78]:
a = np.array([[1,2],[3,4]])

In [79]:
a

array([[1, 2],
       [3, 4]])

In [81]:
a[[1,0]]

array([[3, 4],
       [1, 2]])

In [82]:
import seaborn as sns

In [83]:
tips = sns.load_dataset('tips')

In [84]:
tips.tip

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [85]:
tips['tip']

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [86]:
tips[['tip']]

tip
0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
..    ...
239  5.92
240  2.00
241  2.00
242  1.75
243  3.00

[244 rows x 1 columns]

In [87]:
tips[['sex','tip']]   # 차원유지하니 재조합 가능

sex   tip
0    Female  1.01
1      Male  1.66
2      Male  3.50
3      Male  3.31
4    Female  3.61
..      ...   ...
239    Male  5.92
240  Female  2.00
241    Male  2.00
242    Male  1.75
243  Female  3.00

[244 rows x 2 columns]

https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html

시계열 데이터도 fancy indexing 사용 재조합