<a href="https://colab.research.google.com/github/ukhyun-lee/stock_market_analysis/blob/main/%EC%A4%91%EA%B8%89/19%EC%9D%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B52.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
from sklearn.datasets import load_iris

In [3]:
data = load_iris()

In [4]:
data.data.shape

(150, 4)

In [10]:
import numpy as np

In [11]:
np.unique(data.target, return_counts=True)

(array([0, 1, 2]), array([50, 50, 50]))

In [12]:
input_ = tf.keras.Input(shape=(4,))

In [13]:
layer1 = tf.keras.layers.Dense(16)

In [18]:
activation1 = tf.keras.layers.ReLU()

In [19]:
output = tf.keras.layers.Dense(3)

In [22]:
output(activation1(layer1(input_)))

<KerasTensor: shape=(None, 3) dtype=float32 (created by layer 'dense_4')>

In [ ]:
# Memorization Capacity (w가 많을수록, layer가 많을수록 ) 크면 성능 좋아짐
# 데이터 충분해야 overfitting 되지 않음
# 학습하는데 또 Memorization Capacity 필요해서

In [23]:
input_ = tf.keras.Input(shape=(4,))
x = tf.keras.layers.Dense(16)(input_)
x = tf.keras.layers.ReLU()(x)
output = tf.keras.layers.Dense(3)(x)
# 16,4,3은 임의로

In [24]:
model = tf.keras.models.Model(input_, output)

In [25]:
model

In [28]:
import numpy as np

In [29]:
x = np.array([[1,1,1,1]])

In [30]:
model(x)    # feedforward 자체가 Prediction

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.7397045 , -0.17163745, -0.73272264]], dtype=float32)>

In [26]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_5 (Dense)             (None, 16)                80        
                                                                 
 re_lu_2 (ReLU)              (None, 16)                0         
                                                                 
 dense_6 (Dense)             (None, 3)                 51        
                                                                 
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [ ]:
4*16=64+16=80
3*16=48+3=51

In [27]:
model.weights

[<tf.Variable 'dense_5/kernel:0' shape=(4, 16) dtype=float32, numpy=
 array([[-0.4180975 ,  0.4046859 , -0.22390476, -0.5341304 ,  0.21330214,
          0.03934175,  0.14344132,  0.09986097,  0.45203716,  0.48383117,
          0.02705818, -0.18384501,  0.32146478,  0.51581466,  0.05231196,
          0.38418776],
        [ 0.08846307,  0.1101827 ,  0.07939941,  0.10630387, -0.35884655,
         -0.33593804,  0.0298385 , -0.49016678,  0.46410775, -0.12915638,
          0.34595305, -0.43762788,  0.32461482,  0.47148943, -0.17222655,
          0.2822314 ],
        [-0.1598675 , -0.5383063 , -0.2584153 , -0.35558122, -0.11775875,
         -0.21153319,  0.11366689,  0.17102486,  0.19320774, -0.19563183,
         -0.2839703 , -0.52987325, -0.1528166 , -0.4243008 , -0.4824257 ,
         -0.40829694],
        [ 0.17667383, -0.5272461 ,  0.30197126, -0.27462208, -0.32235694,
         -0.40589702,  0.24843371,  0.45515466,  0.40048784, -0.01634336,
         -0.31119424,  0.23648918, -0.07115346, 

In [5]:
x = tf.keras.Input(shape=(4,))

In [6]:
layer1 = tf.keras.layers.Dense(16)

In [8]:
layer2 = tf.keras.layers.Dense(16)