<a href="https://colab.research.google.com/github/ukhyun-lee/stock_market_analysis/blob/main/%EC%A4%91%EA%B8%89/1%EC%9D%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B54.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# container <> atom(ic) : element 여부에 따라

In [ ]:
'abcde'   12345

In [ ]:
container =>

1. homo vs hetero
2. sequence vs non sequence

In [ ]:
sequence > indexing, slicing

In [1]:
a = 'abcde'

In [2]:
a[0]

'a'

In [3]:
a[2:]

'cde'

In [4]:
a+a

'abcdeabcde'

In [5]:
b = [1,2,3]

In [6]:
b+b

[1, 2, 3, 1, 2, 3]

In [7]:
import numpy as np

In [18]:
x = np.array([1,2,3,4])

In [19]:
x

array([1, 2, 3, 4])

In [22]:
#x = np.array([1,2,3,'4'])

In [23]:
#x

array(['1', '2', '3', '4'], dtype='<U21')

In [13]:
x[0]

1

In [20]:
x[2:]

array([3, 4])

In [21]:
x + x

array([2, 4, 6, 8])

elementwise operation을 하는 특별한 데이터 구조임 <- vector, matrix
#수치해석에 적합한 구조

#수학 연산을 가지고 있지만 기본 파이썬 데이터 구조와 같다.

왜 tensor까지 나왔는지 그리고
R이 아니라 Python이 대세

> 들여쓴 블록



Python 느림, 그러나 코드 작성 시간이 200배 빠름


MATLAB 기능을 Python으로 만들자 opensource 로

느린 단점 해결
동시에 여러 GPU, 여러 프로세서, 여러 컴퓨터 사용으로

Python은 C로 만들어짐

C속도의 버금가게 Python의 장점을 극대화 시킴 =>  NumPy 구조  2005년에 탄생

Python은 머신러닝 역할 키움

google과 facebook도 넘파이 기반으로 GPU가 적용되는 Tensor를 가지고 텐서플로와 파이토치 만듬


2차원 배열
homosequence => array 
넘파이 array는 연산이 수학과 같은 elementwise operation

첫번째 vectorized => 병렬 계산 멀티코어 홯용 => 속도 빠름
넘파이는 대형 배열에 최적화된 라이브러리
GPU 텐서와 파이토치에서도 지원

두번째 쉽다.

1차 Vector
2차 Matrix
3차 3D Array (3rd order Tensor)
N   ND Array

NumPy배워서 -> DataFrame(Table) 조작

컬럼끼리는 데이터형 같음