<a href="https://colab.research.google.com/github/ukhyun-lee/stock_market_analysis/blob/main/%EC%A4%91%EA%B8%89/2%EC%9D%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B52.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

ndarray = n-dimentional / homo / sequence + elementwise

In [2]:
[1, 2, 3 ] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [3]:
'abc' + 'def'

'abcdef'

In [4]:
(1,2,3) + (4, 5, 6)

(1, 2, 3, 4, 5, 6)

In [7]:
np.array([1,2,3]) + np.array([1,2,3])   #=> elementwise 연산 => 수학적 concept

array([2, 4, 6])

# element-wise : shape / dtype  => 수학적 concept

In [11]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[4,5]])

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b

array([[1, 2],
       [4, 5]])

In [14]:
a + b

ValueError: ignored

In [16]:
c = np.array([1,2,3])
d = np.array(['1',2,3])

In [17]:
c

array([1, 2, 3])

In [18]:
d

array(['1', '2', '3'], dtype='<U21')

broadcasting   => 상수, 행 또는 열 피연산자를 맞추어 nparray에 맞게 연산

In [19]:
a    

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a + 5   #=> [[5 5 5]   
        #=>  [5 5 5]]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
a + np.array([3,4,5])

array([[ 4,  6,  8],
       [ 7,  9, 11]])

In [23]:
np.array([3,4,5])    

array([3, 4, 5])

# shape에 따라 연산 방법이 다를 수 있음 => 즉 연산결과

In [24]:
a = np.array([1,2])
b = np.array([3,4])

In [25]:
np.dot(a,b)   # 3 + 8  내적

11

In [26]:
a @ b    # 내적

11

In [27]:
a * b

array([3, 8])

In [36]:
np.multiply(a,b)

array([3, 8])

In [28]:
aa = np.array([[1,2],[1,2]])
bb = np.array([[3,4],[3,4]])

In [34]:
np.dot(aa,bb)  # => 2차원일 경우 행렬곱

array([[ 9, 12],
       [ 9, 12]])

In [31]:
aa @ bb

array([[ 9, 12],
       [ 9, 12]])

In [33]:
aa  * bb

array([[3, 8],
       [3, 8]])

In [35]:
np.multiply(aa, bb)

array([[3, 8],
       [3, 8]])

#ufunc  => universial function

In [37]:
np.add(1,2)

3

In [38]:
np.add([1,2],[3,4])

array([4, 6])

# 

In [39]:
np.lookfor('add')

Search results for 'add'
------------------------
numpy.add
    Add arguments element-wise.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.add_newdoc
    Add documentation to an existing object, typically one defined in C
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.ma.add
    Add arguments element-wise.
numpy.add_docstring
    Add a docstring to a built-in obj if possible.
numpy.quantile
    Compute the q-th quantile of the data along the specified axis.
numpy.deprecate
    Issues a DeprecationWarning, adds warning to `old_name`'s
numpy.array_api.add
    Array API compatible wrapper for :py:func:`np.add <numpy.add>`.
numpy._add_newdoc_ufunc
    Replace the docstring for a ufunc with new_docstring.
numpy.binary_repr
    Return the binary representation of the input number as a string.
numpy.ma.ids
    ids(self)
numpy.ma.append
    Append values to the end of an array.
numpy.bytes0.ljust
    Return a left-j

In [41]:
np.info(np.add)

In [42]:
a = np.arange(12).reshape(4,3)

In [47]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [48]:
a.data

In [49]:
a.strides    #=> 8byte씩 한행은 24byte 이동  axis 연산 한열로 행으로 연산이 아주 빠르다

(24, 8)

In [50]:
a.sum(axis=0)

array([18, 22, 26])

In [53]:
a.max(axis=1)

array([ 2,  5,  8, 11])

In [51]:
a.sum(axis=1)

array([ 3, 12, 21, 30])

In [52]:
a.min(axis=1)

array([0, 3, 6, 9])

In [66]:
a = np.arange(12)

In [64]:
a

[1, 2, 3, 4]

In [67]:
a.reshape(3,4)   # (3,7)은 안됨

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [69]:
a = a.reshape(3,4)   # reaassign : 재할당

In [70]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# mutable, -> inplace  => 재할당하지 않고 (메모리번지를 변경) 자신의 값을 변경

inplace가 mutable연산의 힌트
대부분의 연산은 inplace가 기본이 아님 왜)실수로 바뀔수있으니 


In [57]:
a = [1,2,3,]

In [58]:
id(a)

140476505645184

In [59]:
a.append(4)

In [60]:
a

[1, 2, 3, 4]

In [61]:
id(a)

140476505645184

In [71]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
a.resize(6,2)

In [73]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [74]:
np.split(a,2)

[array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]])]

In [75]:
np.split(a,2, axis=1)

[array([[ 0],
        [ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]]),
 array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]])]

#len테크닉 => unpacking

In [76]:
len(np.split(a,2,axis=1))

2

In [78]:
x, y = np.split(a, 2, axis=1)

In [79]:
x

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [80]:
y

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]])

In [82]:
x, y = np.split(a, 2, axis=0)

In [83]:
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [84]:
np.hsplit(a,2)

[array([[ 0],
        [ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]]),
 array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]])]

In [85]:
np.vsplit(a,2)

[array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]])]

In [86]:
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [87]:
y

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [88]:
np.concatenate((x,y), axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [89]:
np.concatenate((x,y), axis=1)

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [90]:
np.stack((x,y))   #차원증가

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [94]:
np.stack((x,y), axis=1)   #차원증가

array([[[ 0,  1],
        [ 6,  7]],

       [[ 2,  3],
        [ 8,  9]],

       [[ 4,  5],
        [10, 11]]])

In [91]:
np.hstack((x,y))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [92]:
np.vstack((x,y))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [95]:
np.dstack((x,y))

array([[[ 0,  6],
        [ 1,  7]],

       [[ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11]]])

In [96]:
a = [1,2,3]

In [97]:
b = a   #mutable은 메모리를 공유

In [98]:
b[0] =100

In [99]:
a

[100, 2, 3]

In [103]:
a = [1,2,3]

In [105]:
b = a[:]    #=> b = a.copy()

In [106]:
b[0]=100

In [109]:
b

[100, 2, 3]

In [107]:
a

[1, 2, 3]

In [110]:
aa = [[1,2],[3,4]]  # => 1차까지만(shallow) copy 2차는 메모리 공유 

In [111]:
bb = aa.copy()   #shallow

In [113]:
bb[0][0] = 100

In [100]:
c = (1,2,3)    #=> tuple

In [114]:
aa

[[100, 2], [3, 4]]

In [115]:
import copy

In [116]:
aa = [[1,2],[3,4]]

In [117]:
bb = copy.deepcopy(aa)

In [118]:
bb[0][0] = 100

In [119]:
aa

[[1, 2], [3, 4]]

In [101]:
d = c

In [102]:
d[0] =100

TypeError: ignored

In [121]:
a = np.arange(24).reshape(4,6)

In [123]:
b = a.copy()  # shallow (x)  deep(0)

In [125]:
b[0,0] = 100

In [126]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

#copy? why<-ctrl+zb(데이터분석 (numpy에서)
데이터 재복구 어려움 => 돌아갈 수 있는 checkpoint를 만들어놓음