<a href="https://colab.research.google.com/github/ukhyun-lee/stock_market_analysis/blob/main/%EC%A4%91%EA%B8%89/2%EC%9D%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B51.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

array = homo / sequence + elementwise
nd = n-dimentianal (n차원도 만들 수 있음 )

# oop > object : instance 클래스에()

In [ ]:
a = int()   # 클래스에 () -> object 또는 instance  <- type()  :  data type = class

# literal : (특수)문자 > type결정

In [ ]:
a = [1,2,]

In [ ]:
a

[1, 2]

In [ ]:
list((1,2))

[1, 2]

In [ ]:
(1,2)

(1, 2)

In [ ]:
tuple((1,2))

(1, 2)

# factory method : 값을 만드는 함수를 통해서

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
b = np.arange(10)

In [ ]:
b     ## 이름은 type나옴

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(b)  ## print는 type 이 안나옴

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
type(b)

numpy.ndarray

# c.f) repr / str

In [ ]:
class T:
    def __repr__(self):
      return '이름 부를 때 결과'
    def __str__(self):
      return 'print할때 결과'  

In [ ]:
t = T()

In [ ]:
t

이름 부를 때 결과

In [ ]:
print(t)

print할때 결과


In [ ]:
type(a)

numpy.ndarray

In [ ]:
np.ndarray((2,3))

array([[3.16814734e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
b = 0

In [ ]:
type(b)

int

In [ ]:
c = int(0)

In [ ]:
d = [1,2,3]

In [ ]:
type(d)

list

In [ ]:
list((1,2,3))

[1, 2, 3]

# numpy

In [ ]:
a = np.array([[1,2],[3,4]])   ## [[]] 면 2차원 데이터 즉 행렬

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.array([1,2,3,4])    ## [] 면 벡터

In [ ]:
b

array([1, 2, 3, 4])

In [ ]:
c = np.array(([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]))

In [ ]:
c    ## 3차원은 공백이 있음, 우리는 2차원까지만 다룸

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
d = np.arange(10)

In [ ]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(d)

numpy.ndarray

In [ ]:
#numpy = ndarray

In [ ]:
c = np.zeros((2,3))

In [ ]:
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c.ndim 

2

In [ ]:
c.size

6

In [ ]:
c.shape  # ndim 확인 필요 없음

(2, 3)

In [ ]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.eye(3)     #단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(4)  # 정방행렬

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
a= np.array([1,1.,])   # 정수형, 실수형 같이 묵시적/암시적 형변환 시켜줌  (coersion)  -> array는 호모라

In [ ]:
a.dtype    # python + c type    그러므로 C와 유사 타입   , python 타입은 사용안함 (속도가 느려)

dtype('float64')

파이썬 타입 int, float. complex, bool (True, False) 

In [ ]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.float128],
 'complex': [numpy.complex64, numpy.complex128, numpy.complex256],
 'others': [bool, object, bytes, str, numpy.void]}

numpy 메모리에 연속된 공간에 저장 => 빠름

In [ ]:
b = np.array([1,2,3])

In [ ]:
b

array([1, 2, 3])

In [ ]:
b.dtype

dtype('int64')

In [ ]:
b.itemsize

8

#sequence 순서 중요 => 인덱싱과 슬라이싱

In [ ]:
a = np.arange(24).reshape(4,6)

In [ ]:
a  # n 차원을 편하게 index/slicing 하는 기능

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
# 5가지 추가방법

In [ ]:
a[3][4]
a[3,4]
a[-1, -2]

22

In [ ]:
a[3,3:-1]

array([21, 22])

In [ ]:
a[(0,1),(3,2)]

array([3, 8])

In [ ]:
a[(1,2,3),(1,1,2)]

array([ 7, 13, 20])

In [ ]:
#boolean indexing

In [ ]:
a > 5    #broadcasting

array([[False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [ ]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23])

In [ ]:
a[(a>5) & (a<10)] # & / ~

array([6, 7, 8, 9])

In [ ]:
#fancy indexing

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a[[2]]

array([[12, 13, 14, 15, 16, 17]])

In [ ]:
a[[2,3]]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a[[3,2]]

array([[18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17]])

# c.f)

In [ ]:
import tensorflow as tf

In [ ]:
a = tf.constant([1,2,3.])    # coersion 안해줌

In [ ]:
a

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>