<a href="https://colab.research.google.com/github/ukhyun-lee/stock_market_analysis/blob/main/%EC%A4%91%EA%B8%89/7%EC%9D%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B51.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

데이터로부터 specific 문제 해결을 하기 위한 (예측 - 지도/비지도)
최적의 모델 만드는 것/ 선택

In [ ]:
#성능을 (가능한) 정확

In [ ]:
##holdout(우리가 가진 데이터는 대표성/정답)
train - test

In [ ]:
### 데이터가 크면 > 큰 수의 법칙 but data shift 문데 등 고려

In [ ]:
# random하게 sampling, split

In [ ]:
## 여러번 holdout 반복

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
data = load_iris(as_frame=True)

In [ ]:
iris = data.frame

In [ ]:
iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris.iloc[:,:-1], iris.target, stratify=iris.target)

In [ ]:
y_test.value_counts() #=> 분포, 숫자 가 다름 => stratify 후 같게

1    13
2    13
0    12
Name: target, dtype: int64

In [ ]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
139                6.9               3.1                5.4               2.1
97                 6.2               2.9                4.3               1.3
82                 5.8               2.7                3.9               1.2
21                 5.1               3.7                1.5               0.4
48                 5.3               3.7                1.5               0.2
..                 ...               ...                ...               ...
133                6.3               2.8                5.1               1.5
60                 5.0               2.0                3.5               1.0
12                 4.8               3.0                1.4               0.1
129                7.2               3.0                5.8               1.6
32                 5.2               4.1                1.5               0.1

[112 rows x 4 columns]

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier()

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
knn.score(X_test, y_test)

0.9736842105263158

split을 반복 계속 다르게 10번 결과 평균을 냄


#dataset

## 필수 전처리
##missing data
##numerical data(skikit-learn에서는 일부 알고리즘에서는
##target/y는 숫자 아닌값 허용 - 내부적으로 자동으로 변경

#raw
#EDA
#Preprocessig - 전처리
#EDA

#Encoding (embedding)-> ? to numerical

In [ ]:
import seaborn as sns

In [ ]:
tips = sns.load_dataset('tips')

In [ ]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

sex, smoker와 day, time 숫자 관점이 다름(두개, 여러개) (순서없음, 순서있음)

# ordinal(순서있는)
# 기준점, 간격에 따라 성능이 바뀔 수 있음
# 간격이 등간격, 비등간격에 따라 성능이 바뀜

# label(ordinal) encoding => 문자를 단순히 숫자형태로 바꾸는 것

In [ ]:
tips.day.value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [ ]:
tips.time.value_counts()

Dinner    176
Lunch      68
Name: time, dtype: int64

# nominal

#F 0 -1 1
#M 1 1 -1

# one-hot encoding (dummy) => 문제점 (멀티값이 됨)
- F M
- 1 0
- 0 1

# multi-hot  A B C (001 010 100) 배정

# distributed representation => 사과 배 카 (0.2, 0.3, 0,7) 배정

In [ ]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
tips.sex.map({'Female':-1, 'Male':2})

0     -1
1      2
2      2
3      2
4     -1
      ..
239    2
240   -1
241    2
242    2
243   -1
Name: sex, Length: 244, dtype: category
Categories (2, int64): [2, -1]

In [ ]:
tips.sex.map(lambda x: 1 if x=='Female' else 0)

0      1
1      0
2      0
3      0
4      1
      ..
239    0
240    1
241    0
242    0
243    1
Name: sex, Length: 244, dtype: category
Categories (2, int64): [0, 1]

In [ ]:
tips.sex.apply(lambda x: 1 if x=='Female' else 0)

0      1
1      0
2      0
3      0
4      1
      ..
239    0
240    1
241    0
242    0
243    1
Name: sex, Length: 244, dtype: category
Categories (2, int64): [0, 1]

In [ ]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(tips.sex)
le.transform(tips.sex)

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [ ]:
LabelEncoder

sklearn.preprocessing._label.LabelEncoder

In [ ]:
le.fit_transform(tips.sex)

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [ ]:
le.inverse_transform([0,1,1])

array(['Female', 'Male', 'Male'], dtype=object)

In [ ]:
import numpy as np

In [ ]:
tips.sex.cat.categories

Index(['Male', 'Female'], dtype='object')

In [ ]:
ore = OrdinalEncoder(categories=[tips.sex.cat.categories])

In [ ]:
ore = OrdinalEncoder(categories=[['Female','Male']])  # 순서정할 수 있음
#ore = OrdinalEncoder()

In [ ]:
tips.sex

0      Female
1        Male
2        Male
3        Male
4      Female
        ...  
239      Male
240    Female
241      Male
242      Male
243    Female
Name: sex, Length: 244, dtype: category
Categories (2, object): ['Male', 'Female']

In [ ]:
ore.fit_transform(tips[['sex']])

array([[0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],

In [ ]:
ore.inverse_transform([[0],[1],[1]])

array([['Female'],
       ['Male'],
       ['Male']], dtype=object)

In [ ]:
tips['Female'] = (tips.sex=='Female')*1
tips['Male'] = (tips.sex=='Male')*1

In [ ]:
tips

total_bill   tip     sex smoker   day    time  size  F  M  Female  Male
0         16.99  1.01  Female     No   Sun  Dinner     2  1  0       1     0
1         10.34  1.66    Male     No   Sun  Dinner     3  0  1       0     1
2         21.01  3.50    Male     No   Sun  Dinner     3  0  1       0     1
3         23.68  3.31    Male     No   Sun  Dinner     2  0  1       0     1
4         24.59  3.61  Female     No   Sun  Dinner     4  1  0       1     0
..          ...   ...     ...    ...   ...     ...   ... .. ..     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3  0  1       0     1
240       27.18  2.00  Female    Yes   Sat  Dinner     2  1  0       1     0
241       22.67  2.00    Male    Yes   Sat  Dinner     2  0  1       0     1
242       17.82  1.75    Male     No   Sat  Dinner     2  0  1       0     1
243       18.78  3.00  Female     No  Thur  Dinner     2  1  0       1     0

[244 rows x 11 columns]

In [ ]:
tips.drop(columns=['Female','Male'], inplace=True)

In [ ]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
tips['F'] = tips.sex.map(lambda x: 1 if x=='Female' else 0)
tips['M'] = tips.sex.map(lambda x: 1 if x=='Male' else 0)

In [ ]:
tips

total_bill   tip     sex smoker   day    time  size  F  M
0         16.99  1.01  Female     No   Sun  Dinner     2  1  0
1         10.34  1.66    Male     No   Sun  Dinner     3  0  1
2         21.01  3.50    Male     No   Sun  Dinner     3  0  1
3         23.68  3.31    Male     No   Sun  Dinner     2  0  1
4         24.59  3.61  Female     No   Sun  Dinner     4  1  0
..          ...   ...     ...    ...   ...     ...   ... .. ..
239       29.03  5.92    Male     No   Sat  Dinner     3  0  1
240       27.18  2.00  Female    Yes   Sat  Dinner     2  1  0
241       22.67  2.00    Male    Yes   Sat  Dinner     2  0  1
242       17.82  1.75    Male     No   Sat  Dinner     2  0  1
243       18.78  3.00  Female     No  Thur  Dinner     2  1  0

[244 rows x 9 columns]

In [ ]:
import pandas as pd

In [ ]:
pd.get_dummies(tips.sex)*1

Male  Female
0       0       1
1       1       0
2       1       0
3       1       0
4       0       1
..    ...     ...
239     1       0
240     0       1
241     1       0
242     1       0
243     0       1

[244 rows x 2 columns]

In [ ]:
pd.get_dummies(tips[['sex']])

sex_Male  sex_Female
0           0           1
1           1           0
2           1           0
3           1           0
4           0           1
..        ...         ...
239         1           0
240         0           1
241         1           0
242         1           0
243         0           1

[244 rows x 2 columns]

In [ ]:
tips.sex.str.get_dummies()

Female  Male
0         1     0
1         0     1
2         0     1
3         0     1
4         1     0
..      ...   ...
239       0     1
240       1     0
241       0     1
242       0     1
243       1     0

[244 rows x 2 columns]

In [ ]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
 7   F           244 non-null    category
 8   M           244 non-null    category
 9   Female      244 non-null    int64   
 10  Male        244 non-null    int64   
dtypes: category(6), float64(2), int64(3)
memory usage: 11.9 KB


# 고급

In [ ]:
tips.sex.cat.codes

0      1
1      0
2      0
3      0
4      1
      ..
239    0
240    1
241    0
242    0
243    1
Length: 244, dtype: int8

#필수

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
one = OneHotEncoder()

In [ ]:
one.fit_transform(tips[['sex']])

<244x2 sparse matrix of type '<class 'numpy.float64'>'
	with 244 stored elements in Compressed Sparse Row format>

In [ ]:
one.fit_transform(tips[['sex']]).toarray()

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.

In [ ]:
one.inverse_transform([[0,1],[1,0]])

array([['Male'],
       ['Female']], dtype=object)

# y = class = target
# - label encoding
# X = one-hot

In [ ]:
iris = sns.load_dataset('iris')

In [ ]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
pd.get_dummies(iris.species)*1

setosa  versicolor  virginica
0         1           0          0
1         1           0          0
2         1           0          0
3         1           0          0
4         1           0          0
..      ...         ...        ...
145       0           0          1
146       0           0          1
147       0           0          1
148       0           0          1
149       0           0          1

[150 rows x 3 columns]

In [ ]:
iris_ohe= pd.concat([iris, pd.get_dummies(iris.species)*1], axis=1)   #옆으로 더함

In [ ]:
iris_ohe

sepal_length  sepal_width  petal_length  petal_width    species  setosa  \
0             5.1          3.5           1.4          0.2     setosa       1   
1             4.9          3.0           1.4          0.2     setosa       1   
2             4.7          3.2           1.3          0.2     setosa       1   
3             4.6          3.1           1.5          0.2     setosa       1   
4             5.0          3.6           1.4          0.2     setosa       1   
..            ...          ...           ...          ...        ...     ...   
145           6.7          3.0           5.2          2.3  virginica       0   
146           6.3          2.5           5.0          1.9  virginica       0   
147           6.5          3.0           5.2          2.0  virginica       0   
148           6.2          3.4           5.4          2.3  virginica       0   
149           5.9          3.0           5.1          1.8  virginica       0   

     versicolor  virginica  
0             0          0  
1             0          0  
2             0          0  
3             0          0  
4             0          0  
..          ...        ...  
145           0          1  
146           0          1  
147           0          1  
148           0          1  
149           0          1  

[150 rows x 8 columns]

In [ ]:
iris_ohe.drop(columns='species', inplace=True)

In [ ]:
iris_ohe

sepal_length  sepal_width  petal_length  petal_width  setosa  versicolor  \
0             5.1          3.5           1.4          0.2       1           0   
1             4.9          3.0           1.4          0.2       1           0   
2             4.7          3.2           1.3          0.2       1           0   
3             4.6          3.1           1.5          0.2       1           0   
4             5.0          3.6           1.4          0.2       1           0   
..            ...          ...           ...          ...     ...         ...   
145           6.7          3.0           5.2          2.3       0           0   
146           6.3          2.5           5.0          1.9       0           0   
147           6.5          3.0           5.2          2.0       0           0   
148           6.2          3.4           5.4          2.3       0           0   
149           5.9          3.0           5.1          1.8       0           0   

     virginica  
0            0  
1            0  
2            0  
3            0  
4            0  
..         ...  
145          1  
146          1  
147          1  
148          1  
149          1  

[150 rows x 7 columns]

In [ ]:
#X_train, X_test, y_train, y_test = train_test_split(iris_ohe.iloc[:,:-3], iris_ohe.iloc[:,-3:])
X_train,X_test,y_train,y_test = train_test_split(iris_ohe.iloc[:,:-3], iris_ohe.iloc[:,-3:])

In [ ]:
y_train

setosa  versicolor  virginica
127       0           0          1
46        1           0          0
40        1           0          0
56        0           1          0
102       0           0          1
..      ...         ...        ...
146       0           0          1
20        1           0          0
60        0           1          0
45        1           0          0
128       0           0          1

[112 rows x 3 columns]

In [ ]:
X_train

sepal_length  sepal_width  petal_length  petal_width
127           6.1          3.0           4.9          1.8
46            5.1          3.8           1.6          0.2
40            5.0          3.5           1.3          0.3
56            6.3          3.3           4.7          1.6
102           7.1          3.0           5.9          2.1
..            ...          ...           ...          ...
146           6.3          2.5           5.0          1.9
20            5.4          3.4           1.7          0.2
60            5.0          2.0           3.5          1.0
45            4.8          3.0           1.4          0.3
128           6.4          2.8           5.6          2.1

[112 rows x 4 columns]

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier()

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
KNeighborsClassifier

sklearn.neighbors._classification.KNeighborsClassifier

In [ ]:
knn.predict(X_test)

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]], dtype=uint8)

#일부 알고리즘에서는 y/target/class 값이 1d가 아닌 즉, one-hot 등 가능
=> 알고리즘을 알고 있어야 => 에러메세지 보고 찾아야

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression()

In [ ]:
lr.fit(X_train, y_train)

ValueError: ignored

# 결즉치 (missing data) = impute

In [ ]:
mpg = sns.load_dataset('mpg')

In [ ]:
mpg[mpg.horsepower.isna()]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
32   25.0          4          98.0         NaN    2046          19.0   
126  21.0          6         200.0         NaN    2875          17.0   
330  40.9          4          85.0         NaN    1835          17.3   
336  23.6          4         140.0         NaN    2905          14.3   
354  34.5          4         100.0         NaN    2320          15.8   
374  23.0          4         151.0         NaN    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl

In [ ]:
mpg_ = mpg[mpg.horsepower.isna()]

In [ ]:
mpg.fillna(method='ffill')  #fillna(3) forward fill backward fill

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu  
1            70     usa          buick skylark 320  
2            70     usa         plymouth satellite  
3            70     usa              amc rebel sst  
4            70     usa                ford torino  
..          ...     ...                        ...  
393          82     usa            ford mustang gl  
394          82  europe                  vw pickup  
395          82     usa              dodge rampage  
396          82     usa                ford ranger  
397          82     usa                 chevy s-10  

[398 rows x 9 columns]

In [ ]:
mpg_.assign(horsepower=1) # ==> 중요

mpg  cylinders  displacement  horsepower  weight  acceleration  \
32   25.0          4          98.0           1    2046          19.0   
126  21.0          6         200.0           1    2875          17.0   
330  40.9          4          85.0           1    1835          17.3   
336  23.6          4         140.0           1    2905          14.3   
354  34.5          4         100.0           1    2320          15.8   
374  23.0          4         151.0           1    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl

In [ ]:
mpg_.assign(horsepower=lambda x:x.cylinders)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
32   25.0          4          98.0           4    2046          19.0   
126  21.0          6         200.0           6    2875          17.0   
330  40.9          4          85.0           4    1835          17.3   
336  23.6          4         140.0           4    2905          14.3   
354  34.5          4         100.0           4    2320          15.8   
374  23.0          4         151.0           4    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl

#row, column

In [ ]:
mpg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [ ]:
mpg_

mpg  cylinders  displacement  horsepower  weight  acceleration  \
32   25.0          4          98.0         NaN    2046          19.0   
126  21.0          6         200.0         NaN    2875          17.0   
330  40.9          4          85.0         NaN    1835          17.3   
336  23.6          4         140.0         NaN    2905          14.3   
354  34.5          4         100.0         NaN    2320          15.8   
374  23.0          4         151.0         NaN    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl

In [ ]:
from sklearn.impute import SimpleImputer    #=> Imputer 3개

In [ ]:
ssi = SimpleImputer(strategy='constant', fill_value=1000)

In [ ]:
ssi.fit_transform(mpg[['horsepower']])

array([[130.        ],
       [165.        ],
       [150.        ],
       [150.        ],
       [140.        ],
       [198.        ],
       [220.        ],
       [215.        ],
       [225.        ],
       [190.        ],
       [170.        ],
       [160.        ],
       [150.        ],
       [225.        ],
       [ 95.        ],
       [ 95.        ],
       [ 97.        ],
       [ 85.        ],
       [ 88.        ],
       [ 46.        ],
       [ 87.        ],
       [ 90.        ],
       [ 95.        ],
       [113.        ],
       [ 90.        ],
       [215.        ],
       [200.        ],
       [210.        ],
       [193.        ],
       [ 88.        ],
       [ 90.        ],
       [ 95.        ],
       [104.46938776],
       [100.        ],
       [105.        ],
       [100.        ],
       [ 88.        ],
       [100.        ],
       [165.        ],
       [175.        ],
       [153.        ],
       [150.        ],
       [180.        ],
       [170

In [ ]:
from sklearn.impute import KNNImputer

In [ ]:
knni = KNNImputer()   # 전체 평균이 아닌 나하고 가까운 값 5개 찾아 평균

In [ ]:
knni.fit_transform(mpg[['horsepower']])

array([[130.        ],
       [165.        ],
       [150.        ],
       [150.        ],
       [140.        ],
       [198.        ],
       [220.        ],
       [215.        ],
       [225.        ],
       [190.        ],
       [170.        ],
       [160.        ],
       [150.        ],
       [225.        ],
       [ 95.        ],
       [ 95.        ],
       [ 97.        ],
       [ 85.        ],
       [ 88.        ],
       [ 46.        ],
       [ 87.        ],
       [ 90.        ],
       [ 95.        ],
       [113.        ],
       [ 90.        ],
       [215.        ],
       [200.        ],
       [210.        ],
       [193.        ],
       [ 88.        ],
       [ 90.        ],
       [ 95.        ],
       [104.46938776],
       [100.        ],
       [105.        ],
       [100.        ],
       [ 88.        ],
       [100.        ],
       [165.        ],
       [175.        ],
       [153.        ],
       [150.        ],
       [180.        ],
       [170

In [ ]:
from sklearn.impute import IterativeImputer

ImportError: ignored

In [ ]:
from sklearn.experimental import enable_iterative_imputer

In [ ]:
from sklearn.impute import IterativeImputer

In [ ]:
iit = IterativeImputer()

In [ ]:
iit.fit_transform(mpg[['horsepower']])  => 마이스 technique 머신러닝 테크닉을 사용하여 채움

array([[130.        ],
       [165.        ],
       [150.        ],
       [150.        ],
       [140.        ],
       [198.        ],
       [220.        ],
       [215.        ],
       [225.        ],
       [190.        ],
       [170.        ],
       [160.        ],
       [150.        ],
       [225.        ],
       [ 95.        ],
       [ 95.        ],
       [ 97.        ],
       [ 85.        ],
       [ 88.        ],
       [ 46.        ],
       [ 87.        ],
       [ 90.        ],
       [ 95.        ],
       [113.        ],
       [ 90.        ],
       [215.        ],
       [200.        ],
       [210.        ],
       [193.        ],
       [ 88.        ],
       [ 90.        ],
       [ 95.        ],
       [104.46938776],
       [100.        ],
       [105.        ],
       [100.        ],
       [ 88.        ],
       [100.        ],
       [165.        ],
       [175.        ],
       [153.        ],
       [150.        ],
       [180.        ],
       [170

EDA
=> 필수전처리
Missing Data
Feature Extraction (One hot encoding, Label encoding)

=> 성능을 높히기 위한 전처리

=>머신러닝